import './globals.css'
import { Montserrat } from 'next/font/google'
import type { Metadata } from 'next'

import NavBar from './components/NavBar/NavBar'

const montserrat = Montserrat({
	subsets: ['latin'],
	weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
	fallback: ['sans-serif', 'system-ui'],
})

export const metadata: Metadata = {
	title: 'Default Layout Meta',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {

	return (
		<html lang="en">
			<body className={montserrat.className}>
				<NavBar />
				{children}
			</body>
		</html>
	)
}
